# This is a basic workflow to help you get started with Actions

name: deploy-to-azure

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      appName:
        type: string
        default: logicapp-cicd
      env:
        type: string      
        default: test
        values:
        - test
        - prod 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: rg-${{ inputs.env }}-logicapp
        template: ./main.bicep
        parameters: 'env=${{ inputs.env }} appName=${{ inputs.appName }} subId=${{ secrets.AZURE_SUBSCRIPTION }}'
        failOnStdErr: false
